
server:
  servlet:
    context-path: /bank
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bank_db"
    username: root
    password: manhden123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




jwt:
  signerKey: "/F70vejt8f73kCzBypDPo7D7SrfrLKV3OLqWC24RhXyQPDOPUxx+XWV56M867PzE"

logging:
  level:
    org.springframework.cache: debug
