#spring.application.name=Bank
#server.servlet.context-path=/bank
## Database
#spring.datasource.url=jdbc:mysql://localhost:3306/bank_db
#spring.datasource.username=root
#spring.datasource.password=manhden123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
##spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
## Server
#server.port=8080
## JWT (s? d?ng sau)
#jwt.secret="bank1234secret"
#jwt.expiration=86400000

server:
  servlet:
    context-path: /bank
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bank_db"
    username: root
    password: manhden123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "ZdvNMDHyNDEhxmiBpJy4ZLTnvdeaXursPU5Es/3LyPfn6uVUHC2xq0E+JASVForD"

